sudo: required #is required to use docker service in travis

env:
  global:
    - image_name=springboot
    - ecr_account=223613412620

language: java

services:
  - docker


install:
  - echo "install nothing!" # put your normal pre-testing installs here

script: mvn clean compile package



after_script:
    - 'curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
    - 'unzip awscli-bundle.zip'
    - './awscli-bundle/install -b ~/bin/aws'
    - 'export PATH=~/bin:$PATH'
    - eval $(aws ecr get-login --region eu-west-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
    - docker build -t $image_name .
    - docker tag $image_name:latest $ecr_account.dkr.ecr.eu-west-1.amazonaws.com/$image_name:latest
    - docker push $ecr_account.dkr.ecr.eu-west-1.amazonaws.com/$image_name:latest

