
language: java
env:
  - image_name=springboot
  - docker_hub=bucinkocloud


services:
  - docker
sudo: false
script: mvn clean compile package


after_script:
  - docker build -t $docker_hub/$image_name .
  - echo "$DOCKER_PASSWORD" | docker login -u bucinkocloud --password-stdin
  - docker push $docker_hub/$image_name:latest
